dataSources:
  ds0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/tcbiz_ins?characterEncoding=utf8&useAffectedRows=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456

rules:
  - !SHARDING
    tables:
      cash_repay_apply:
        logicTable: cash_repay_apply
        actualDataNodes: ds0.cash_repay_apply_0$->{0..9},ds0.cash_repay_apply_$->{10..49}
        tableStrategy:
          standard:
            shardingColumn: memberId
            shardingAlgorithmName: memberId-mode-50
    shardingAlgorithms:
      memberId-mode-50:
        type: INLINE
        props:
          algorithm-expression: cash_repay_apply_${memberId % 50}

props:
  sql-show: true