dataSources:
  ds0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/tcbiz_ins?characterEncoding=utf8&useAffectedRows=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Zhang520620

rules:
  - !SHARDING
    tables:
      #表名
      cash_repay_apply:
        #数据节点，所有表名
        actualDataNodes: ds0.cash_repay_apply_0$->{0..9},ds0.cash_repay_apply_$->{10..49}
        #分表策略
        tableStrategy:
          #分表类型，单列作为分表键
          standard:
            shardingColumn: member_id #分表列
            shardingAlgorithmName: memberId-suffix-mode-50 #分表算法名称，与下面对应
    shardingAlgorithms:
      memberId-suffix-mode-50:
        type: INLINE
        props:
          #分片表达式，groovy 脚本
          algorithm-expression: cash_repay_apply_$->{Long.parseLong(member_id) % 50}

props:
  sql-show: true


# algorithm-expression 报错 Long.parseLong(member_id)
# shardingsphere-springboot-starter 不再维护
# shardingAlgorithms 只提供了 INLINE